#! /usr/local/bin/python3

import re
# from functools import reduce, lru_cache
# from collections import deque
# from itertools import count, islice

INPUT_FILE = f'{__file__}.input'
TEST_FILE = 'test.input'

def parse(file):
  with open(file) as input:
    return (line.strip() for line in input.readlines())

PAIRS = {
  '[' : ']',
  '{' : '}',
  '(' : ')',
  '<' : '>',
}

ILLEGAL_SCORE = {
  ']' : 57,
  '}' : 1197,
  ')' : 3,
  '>' : 25137,
}

def score_for_line(line):
  stack = []
  chars = (char for char in line)
  return score_for_line_rec(chars, stack)

def score_for_line_rec(char_gen, stack):
  try:
    char = next(char_gen)
    if char in '[{(<' : return score_for_line_rec(char_gen, stack + [char])
    expected = PAIRS[stack.pop()]
    if char != expected:
      return ILLEGAL_SCORE[char]
    return score_for_line_rec(char_gen, stack)
  except StopIteration:
    return 0

COMPLETION_SCORE = {
  ']' : 2,
  '}' : 3,
  ')' : 1,
  '>' : 4,
}

def score_for_line_completion(line):
  stack = []
  chars = (char for char in line)
  return score_for_line_completion_rec(chars, stack)

def score_for_line_completion_rec(char_gen, stack):
  try:
    char = next(char_gen)
    if char in '[{(<' : return score_for_line_completion_rec(char_gen, stack + [char])
    expected = PAIRS[stack.pop()]
    if char != expected:
      raise Exception("should not happen")
    return score_for_line_completion_rec(char_gen, stack)
  except StopIteration:
    # count what's left in the stack
    score = 0
    while len(stack) > 0:
      expected = PAIRS[stack.pop()]
      score = score * 5 + COMPLETION_SCORE[expected]
    return score

def process_part_1(input):
  return sum(score_for_line(line) for line in input)

def process_part_2(input):
  valid_lines = (line for line in input if score_for_line(line) == 0)
  scores = [score_for_line_completion(line) for line in valid_lines]
  return sorted(scores)[len(scores) // 2]

assert process_part_1(parse(TEST_FILE)) == 26397
assert process_part_2(parse(TEST_FILE)) == 288957

print(process_part_1(parse(INPUT_FILE)))
print(process_part_2(parse(INPUT_FILE)))