#! /usr/local/bin/python3
INPUT_FILE = f'{__file__}.input'

def parse(file):
  with open(file) as input:
    return list((line.strip().split('-') for line in input.readlines()))

def edges_from_input(input):
  edges = {}
  for a, b in input:
    edges.setdefault(a, set())
    edges.setdefault(b, set())
    edges[a].add(b)
    edges[b].add(a)
  return edges

def is_large(cave):
  return cave[0] >= 'A' and cave[0] <= 'Z'

def process_part_1(input):
  edges = edges_from_input(input)
  paths = []

  def find_ways(current='start', path=['start']):
    if current == 'end':
      paths.append(','.join(path))
      return
    for node in edges[current]:
      if node not in path or is_large(node):
        find_ways(node, path + [node])

  find_ways()
  return len(paths)

def process_part_2(input):
  edges = edges_from_input(input)
  paths = []

  def find_ways(current='start', path=['start'], double_visit=False):
    if current == 'end':
      paths.append(','.join(path))
      return
    for node in edges[current]:
      if (node not in path or is_large(node)):
        find_ways(node, path + [node], double_visit)
      elif (double_visit == False and node not in ['start', 'end']):
        find_ways(node, path + [node], True)
  
  find_ways()
  return len(paths)

example_1 = [['start', 'A'], ['start', 'b'], ['A', 'c'], ['A', 'b'], ['b', 'd'], ['A', 'end'], ['b', 'end']]
assert process_part_1(example_1) == 10
assert process_part_2(example_1) == 36

example_2 = [['dc', 'end'], ['HN', 'start'], ['start', 'kj'], ['dc', 'start'], ['dc', 'HN'], ['LN', 'dc'], ['HN', 'end'], ['kj', 'sa'], ['kj', 'HN'], ['kj', 'dc']]
assert process_part_1(example_2) == 19
assert process_part_2(example_2) == 103

print(process_part_1(parse(INPUT_FILE)))
print(process_part_2(parse(INPUT_FILE)))
