#! /usr/local/bin/python3
import re
from functools import reduce

INPUT_FILE = f'{__file__}.input'
TEST_FILE = 'test.input'

def parse(file):
  LINE_PATTERN = re.compile(r'^(?P<direction>\w+) (?P<number>\d+)(\s|$)')
  def parse_line(line):
    match = LINE_PATTERN.search(line)
    direction, number = match.group('direction'), int(match.group('number'))
    return (direction, number)

  with open(file) as input:
    return (parse_line(line) for line in input.readlines())

def process_part_1(input):
  movements = {
    'up' : lambda number, h, d : (h, d - number),
    'down' : lambda number, h, d : (h, d + number),
    'forward' : lambda number, h, d : (h + number, d)
  }
  def aux(acc, element):
    direction, number = element
    return movements[direction](number, *acc)
  return reduce(aux, input, (0,0))

def process_part_2(input):
  movements = {
    'up' : lambda number, h, d, a : (h, d, a - number),
    'down' : lambda number, h, d, a : (h, d, a + number),
    'forward' : lambda number, h, d, a : (h + number, d + a*number, a)
  }
  def aux(acc, element):
    direction, number = element
    return movements[direction](number, *acc)
  return reduce(aux, input, (0,0,0))

horizontal, depth = process_part_1(parse(INPUT_FILE))
print(f'Final position:{(horizontal, depth)}, result: {horizontal * depth}')

horizontal, depth, aim = process_part_2(parse(INPUT_FILE))
print(f'Final position:{(horizontal, depth, aim)}, result: {horizontal * depth}')