#! /usr/local/bin/python3
INPUT_FILE = f'{__file__}.input'

def parse(file):
  with open(file) as input:
    numbers = input.read().strip().split(',')
    input = [int(number) for number in numbers]
    return initial_state_from_input(input)

def initial_state_from_input(input):
  return [input.count(i) for i in range(9)]

def fish_simulator(a,b,c,d,e,f,g,h,i):
  while True:
    a,b,c,d,e,f,g,h,i = b,c,d,e,f,g,h + a,i,a
    yield a+b+c+d+e+f+g+h+i

def nb_of_fish_at_gen(x, initial_state):
  fish_sim = fish_simulator(*initial_state)
  for _ in range(x):
    result = next(fish_sim)
  return result

print(nb_of_fish_at_gen(80, parse(INPUT_FILE)))
print(nb_of_fish_at_gen(256, parse(INPUT_FILE)))

test_input = [3,4,3,1,2]
assert nb_of_fish_at_gen(80, initial_state_from_input(test_input)) == 5934
assert nb_of_fish_at_gen(256, initial_state_from_input(test_input)) == 26984457539