#! /usr/local/bin/python3

import re
# from functools import reduce, lru_cache
# from collections import deque
# from itertools import count, islice

INPUT_FILE = f'{__file__}.input'
TEST_FILE = 'test.input'

def parse(file):
  LINE_PATTERN = re.compile(r'^(?P<name>\w+) (?P<number>\d+)(\s|$)')
  def parse_line(line):
    match = LINE_PATTERN.search(line)
    name, number = match.group('name'), int(match.group('number'))
    data = match.groupdict()
    print(data)
    return (name, number)

  with open(file) as input:
    return (parse_line(line) for line in input.readlines())

def process(input):
  names = (name for name, number in input if number > 10)
  return '\n'.join(names)

input = parse(INPUT_FILE)
print(process(input))